background="{background}"
surface="{surface}"
overlay="{overlay}"

muted="{muted}"
subtle="{subtle}"
text="{text}"

primary="{primary}"
secondary="{secondary}"
accent="{accent}"

highlight="{highlight}"
